package com.genesis.p2p.core;

import com.genesis.p2p.testutil.base.BaseUnitTest;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("MessageHeader Tests")
class MessageHeaderTest extends BaseUnitTest {

    @Test
    @DisplayName("Should create header with all fields")
    void testCreateHeader() {
        MessageHeader header = new MessageHeader(
            "msg-123",        // messageId
            "corr-456",       // correlationId
            "1.0",            // protocolVersion
            "1.0",            // messageVersion
            10,               // ttl
            0,                // hopCount
            "HELLO",          // type
            "sender-123",     // from
            "receiver-456",   // to
            System.currentTimeMillis(), // timestamp
            false,            // encrypted
            "application/json", // contentType
            false,            // authenticated
            null,             // signature
            false             // requiresAck
        );

        assertNotNull(header);
        assertEquals("msg-123", header.messageId());
        assertEquals("HELLO", header.type());
        assertEquals("sender-123", header.from());
        assertEquals("receiver-456", header.to());
        assertEquals(10, header.ttl());
    }

    @Test
    @DisplayName("Should have valid timestamp")
    void testTimestamp() {
        long before = System.currentTimeMillis();

        MessageHeader header = new MessageHeader(
            null, null, null, null, 10, 0, "TEST", "sender", "receiver",
            System.currentTimeMillis(), false, "text/plain", false, null, false
        );

        long after = System.currentTimeMillis();

        assertTrue(header.timestamp() >= before);
        assertTrue(header.timestamp() <= after);
    }

    @Test
    @DisplayName("Should throw on empty type")
    void testEmptyType() {
        assertThrows(IllegalArgumentException.class, () -> new MessageHeader(
            null, null, null, null, 10, 0, "", "sender", "receiver",
            System.currentTimeMillis(), false, "text/plain", false, null, false
        ));
    }

    @Test
    @DisplayName("Should throw on empty sender")
    void testEmptySender() {
        assertThrows(IllegalArgumentException.class, () -> new MessageHeader(
            null, null, null, null, 10, 0, "TEST", "", "receiver",
            System.currentTimeMillis(), false, "text/plain", false, null, false
        ));
    }

    @Test
    @DisplayName("Should generate messageId if null")
    void testAutoGeneratedId() {
        MessageHeader header = new MessageHeader(
            null, null, null, null, 10, 0, "TEST", "sender", "receiver",
            System.currentTimeMillis(), false, "text/plain", false, null, false
        );

        assertNotNull(header.messageId());
        assertFalse(header.messageId().isEmpty());
    }
}
